### ISSUE TITLE
ls: reading directory .: Input/output error (recurrent on "root" folder)

### ISSUE THREAD

**Issue by beankylla** [ovh/svfs#57] opened 2016-05-17 18:32 UTC
Hello (I'm not saying how much of a fan I am each time anymore because, well I'm here ;))!

whenever listing folders of the hubic root, i get either the following error:

ls: reading directory .: Input/output error

or an incomplete  list.

Same thing happens in file browser.

Once I get one folder deeper however, no problem at all.

Is that (once more) something I did not read right?

Thanks and have a nice day! :)

**Comment by xlucas** [comment] 2016-05-17 20:12
That's odd, can you detail your mount options ?

Also, I can't do much without the debug log, can you unmount, add `debug=true` to your mount options, remount and post the full output when this happens ?

**Comment by beankylla** [comment] 2016-05-17 21:38
Hello,

So I mounted using:
`sudo mount -t svfs -o hubic_auth=blablabla,hubic_token=blablabla,container=default,default_perm=false,debug=true, hubic /cloud/`

then I issued the ls & ls -a commands with the following results:

`_x@x /cloud $ ls
ls: reading directory .: Input/output error
x@x /cloud $ ls -a
ls: reading directory .: Input/output error
1  2  .ovhPub  3  4_`

I guess the ".ovhPub" folder is something I should expect but I have 5 folders not 4 so one is missing. (happy surprise though usually I only get 2 or 0)

the output is:

`2016/05/17 23:29:03 FUSE: <- Access [ID=0x2 Node=0x1 Uid=1000 Gid=1000 Pid=3770] mask=0x4 2016/05/17 23:29:03 FUSE: -> [ID=0x2] Access 2016/05/17 23:29:03 FUSE: <- Lookup [ID=0x3 Node=0x1 Uid=1000 Gid=1000 Pid=3770] ".Trash" 2016/05/17 23:29:03 FUSE: -> [ID=0x3] Lookup error=ENOENT 2016/05/17 23:29:03 FUSE: <- Lookup [ID=0x4 Node=0x1 Uid=1000 Gid=1000 Pid=3770] ".Trash-1000" 2016/05/17 23:29:03 FUSE: -> [ID=0x4] Lookup error=ENOENT 2016/05/17 23:29:15 FUSE: <- Statfs [ID=0x5 Node=0x1 Uid=1000 Gid=1000 Pid=3724] 2016/05/17 23:29:15 FUSE: -> [ID=0x5] Statfs blocks=0/0/0 files=0/0 bsize=0 frsize=0 namelen=0 2016/05/17 23:29:20 FUSE: <- Getattr [ID=0x6 Node=0x1 Uid=1000 Gid=1000 Pid=3962] 0x0 fl=0 2016/05/17 23:29:20 FUSE: -> [ID=0x6] Getattr valid=1m0s ino=1 size=532542671332 mode=drwx------ 2016/05/17 23:29:21 FUSE: <- Access [ID=0x7 Node=0x1 Uid=1000 Gid=1000 Pid=3944] mask=0x1 2016/05/17 23:29:21 FUSE: -> [ID=0x7] Access 2016/05/17 23:29:21 FUSE: <- Open [ID=0x8 Node=0x1 Uid=1000 Gid=1000 Pid=3963] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock 2016/05/17 23:29:21 FUSE: -> [ID=0x8] Open 0x1 fl=0 2016/05/17 23:29:21 FUSE: <- Read [ID=0x9 Node=0x1 Uid=1000 Gid=1000 Pid=3963] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock 2016/05/17 23:29:21 FUSE: -> [ID=0x9] Read 312 2016/05/17 23:29:21 FUSE: <- Release [ID=0xa Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0 2016/05/17 23:29:21 FUSE: -> [ID=0xa] Release 2016/05/17 23:29:29 FUSE: <- Statfs [ID=0xb Node=0x1 Uid=1000 Gid=1000 Pid=3724] 2016/05/17 23:29:29 FUSE: -> [ID=0xb] Statfs blocks=0/0/0 files=0/0 bsize=0 frsize=0 namelen=0 2016/05/17 23:29:43 FUSE: <- Statfs [ID=0xc Node=0x1 Uid=1000 Gid=1000 Pid=3724] 2016/05/17 23:29:43 FUSE: -> [ID=0xc] Statfs blocks=0/0/0 files=0/0 bsize=0 frsize=0 namelen=0 2016/05/17 23:29:44 FUSE: <- Open [ID=0xd Node=0x1 Uid=1000 Gid=1000 Pid=3965] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock 2016/05/17 23:29:44 FUSE: -> [ID=0xd] Open 0x1 fl=0 2016/05/17 23:29:44 FUSE: <- Read [ID=0xe Node=0x1 Uid=1000 Gid=1000 Pid=3965] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock 2016/05/17 23:29:44 FUSE: -> [ID=0xe] Read 312 2016/05/17 23:29:44 FUSE: <- Lookup [ID=0xf Node=0x1 Uid=1000 Gid=1000 Pid=3965] ".ovhPub" 2016/05/17 23:29:44 FUSE: -> [ID=0xf] Lookup 0x2 gen=0 valid=1m0s attr={valid=1m0s ino=17098064227788230404 size=4096 mode=drwx------} 2016/05/17 23:29:44 FUSE: <- Lookup [ID=0x10 Node=0x1 Uid=1000 Gid=1000 Pid=3965] "1" 2016/05/17 23:29:44 FUSE: -> [ID=0x10] Lookup 0x3 gen=0 valid=1m0s attr={valid=1m0s ino=12334951539984183433 size=4096 mode=drwx------} 2016/05/17 23:29:44 FUSE: <- Lookup [ID=0x11 Node=0x1 Uid=1000 Gid=1000 Pid=3965] "2" 2016/05/17 23:29:44 FUSE: -> [ID=0x11] Lookup 0x4 gen=0 valid=1m0s attr={valid=1m0s ino=7351975847773898335 size=4096 mode=drwx------} 2016/05/17 23:29:44 FUSE: <- Lookup [ID=0x12 Node=0x1 Uid=1000 Gid=1000 Pid=3965] "3" 2016/05/17 23:29:44 FUSE: -> [ID=0x12] Lookup 0x5 gen=0 valid=1m0s attr={valid=1m0s ino=13191114144507324609 size=4096 mode=drwx------} 2016/05/17 23:29:44 FUSE: <- Lookup [ID=0x13 Node=0x1 Uid=1000 Gid=1000 Pid=3965] "4" 2016/05/17 23:29:44 FUSE: -> [ID=0x13] Lookup 0x6 gen=0 valid=1m0s attr={valid=1m0s ino=13631154463343777059 size=4096 mode=drwx------} 2016/05/17 23:29:44 FUSE: <- Read [ID=0x14 Node=0x1 Uid=1000 Gid=1000 Pid=3965] 0x1 4096 @0xa0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock 2016/05/17 23:29:44 FUSE: -> [ID=0x14] Read 152 2016/05/17 23:29:44 FUSE: <- Release [ID=0x15 Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0`

Does that help? :)
Do you need anything else? ;)

**Comment by beankylla** [comment] 2016-05-17 21:40
I then did:

`x@x /cloud $ ls
ls: reading directory .: Input/output error
x@x /cloud $ ls -a
ls: reading directory .: Input/output error
.ovhPub`

And got:

`2016/05/17 23:38:48 FUSE: <- Open [ID=0x3c Node=0x1 Uid=1000 Gid=1000 Pid=4090] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/17 23:38:48 FUSE: -> [ID=0x3c] Open 0x1 fl=0
2016/05/17 23:38:48 FUSE: <- Read [ID=0x3d Node=0x1 Uid=1000 Gid=1000 Pid=4090] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/17 23:38:48 FUSE: -> [ID=0x3d] Read 312
2016/05/17 23:38:48 FUSE: <- Read [ID=0x3e Node=0x1 Uid=1000 Gid=1000 Pid=4090] 0x1 4096 @0x20 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/17 23:38:48 FUSE: -> [ID=0x3e] Read 280
2016/05/17 23:38:48 FUSE: <- Release [ID=0x3f Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0
2016/05/17 23:38:48 FUSE: -> [ID=0x3f] Release
2016/05/17 23:38:49 FUSE: <- Statfs [ID=0x40 Node=0x1 Uid=1000 Gid=1000 Pid=3724]
2016/05/17 23:38:49 FUSE: -> [ID=0x40] Statfs blocks=0/0/0 files=0/0 bsize=0 frsize=0 namelen=0
2016/05/17 23:38:53 FUSE: <- Open [ID=0x41 Node=0x1 Uid=1000 Gid=1000 Pid=4091] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/17 23:38:53 FUSE: -> [ID=0x41] Open 0x1 fl=0
2016/05/17 23:38:53 FUSE: <- Read [ID=0x42 Node=0x1 Uid=1000 Gid=1000 Pid=4091] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/17 23:38:53 FUSE: -> [ID=0x42] Read 312
2016/05/17 23:38:53 FUSE: <- Read [ID=0x43 Node=0x1 Uid=1000 Gid=1000 Pid=4091] 0x1 4096 @0x20 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/17 23:38:53 FUSE: -> [ID=0x43] Read 280
2016/05/17 23:38:53 FUSE: <- Release [ID=0x44 Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0
2016/05/17 23:38:53 FUSE: -> [ID=0x44] Release
2016/05/17 23:38:57 FUSE: <- Open [ID=0x45 Node=0x1 Uid=1000 Gid=1000 Pid=4138] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/17 23:38:57 FUSE: -> [ID=0x45] Open 0x1 fl=0
2016/05/17 23:38:57 FUSE: <- Read [ID=0x46 Node=0x1 Uid=1000 Gid=1000 Pid=4138] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/17 23:38:57 FUSE: -> [ID=0x46] Read 312
2016/05/17 23:38:57 FUSE: <- Lookup [ID=0x47 Node=0x1 Uid=1000 Gid=1000 Pid=4138] ".ovhPub"
2016/05/17 23:38:57 FUSE: -> [ID=0x47] Lookup 0x7 gen=0 valid=1m0s attr={valid=1m0s ino=17098064227788230404 size=4096 mode=drwx------}
2016/05/17 23:38:57 FUSE: <- Forget [ID=0x48 Node=0x7 Uid=0 Gid=0 Pid=0] 1
2016/05/17 23:38:57 FUSE: -> [ID=0x48] Forget
2016/05/17 23:38:57 FUSE: <- Lookup [ID=0x4a Node=0x1 Uid=1000 Gid=1000 Pid=4138] ".ovhPub"
2016/05/17 23:38:57 FUSE: -> [ID=0x4a] Lookup 0x7 gen=1 valid=1m0s attr={valid=1m0s ino=17098064227788230404 size=4096 mode=drwx------}
2016/05/17 23:38:57 FUSE: <- Forget [ID=0x49 Node=0x2 Uid=0 Gid=0 Pid=0] 1
2016/05/17 23:38:57 FUSE: -> [ID=0x49] Forget
2016/05/17 23:38:57 FUSE: <- Read [ID=0x4b Node=0x1 Uid=1000 Gid=1000 Pid=4138] 0x1 4096 @0x20 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2016/05/17 23:38:57 FUSE: -> [ID=0x4b] Read 280
2016/05/17 23:38:57 FUSE: <- Release [ID=0x4c Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0
2016/05/17 23:38:57 FUSE: -> [ID=0x4c] Release
2016/05/17 23:39:03 FUSE: <- Statfs [ID=0x4d Node=0x1 Uid=1000 Gid=1000 Pid=3724]
2016/05/17 23:39:03 FUSE: -> [ID=0x4d] Statfs blocks=0/0/0 files=0/0 bsize=0 frsize=0 namelen=0`

(just so we had another example with no return at all ^^

**Comment by xlucas** [comment] 2016-05-19 20:53
It appears no error is thrown by the fuse layer so I'm not sure how svfs is responsible for this behaviour.

What's your OS & arch ?

**Comment by beankylla** [comment] 2016-05-20 06:02
I have on computer on debian 8 (LMDE2) and a nuc on ubuntu server 14, both 64 bits. Happens on both of them.

Both have standard repo configurations (with the same issue):

Debian 8 fuse version: 2.9.3-15+deb8u2
Ubuntu 14 fuse version: 2.9.2-4ubuntu4.14.04.1 

I got over the issue by creating symlinks and never accessing stuff through the main folder / not creating new ones.

**Comment by xlucas** [comment] 2016-05-20 14:59
Unfortunately I cannot reproduce this while using exactly the same OS, Arch and fuse version.

Did you use your hubic account with an other fuse-based solution before like hubicfuse / cloudfs ?

**Comment by beankylla** [comment] 2016-05-20 16:20
I actually have tested at least one and probably both of those solutions!

Interesting! how could that ever be linked?

**Comment by xlucas** [comment] 2016-05-24 08:25
I'm wondering if that can be caused by some feature in one of these. Did you create symlinks or that kind of thing in your container's root ?

**Comment by beankylla** [comment] 2016-05-24 08:27
Not that I'm aware of, i wouldn't really see the point. I created symblinks to access the folder of my containers root but just with svfs.

**Comment by xlucas** [comment] 2016-05-24 09:08
Ok, I will need 2 things to investigate this further, since I cannot reproduce your issue.

##### 1) Post the listing of your container's root

- Install `python-swiftclient` either with your package manager or with `pip`.
- Go to the [hubic API](https://api.hubic.com/console) login and make a call to */account/credentials*. You will fetch a token and an endpoint URL.

Then post the result of : 
```
swift --os-storage-url <endpoint> --os-auth-token <token> list --lh default --delim "/"
```
##### 2) Create a fresh container and check if the same error comes up

To create a new container : 

```
swift --os-storage-url <endpoint> --os-auth-token <token> post <name>
```

Mount the svfs device with `container=<name>`. Create directories in this container's root, push some files in them, umount it and remount it. Then check if the error happens again.

To delete your container afterwards (must be empty) :

```
swift --os-storage-url <endpoint> --os-auth-token <token> delete <name>
swift --os-storage-url <endpoint> --os-auth-token <token> delete <name>_segments
```

**Comment by xlucas** [comment] 2016-06-01 15:56
Closing, will reopen if given more information.

**Closed by xlucas** 2016-06-01 15:56 UTC
Labels: can't reproduce, undefined
